### ISSUE TITLE
build vaapi enabled ffmpeg

### ISSUE THREAD

**Issue by gpregger** [BtbN/FFmpeg-Builds#88] opened 2021-07-05 23:24 UTC
Hi
I've been looking all over for an up to date linux64 build of ffmpeg that has vaapi HW acceleration enabled.
I tried my darndest to get your environment to build it for me but I can't for the life of me pull it off.
Do you think you could provide an option to compile ffmpeg with vaapi or give some pointers?
Many thanks :)

**Comment by BtbN** [comment] 2021-07-05 23:34
I left it out since I assumed it would struggle being used as a static library.
Do you know if it supports that mode of operation?
Dynamically linking it is not an option, since the binary would stop working for people without a recent enough libva version then.

**Comment by gpregger** [comment] 2021-07-05 23:51
You're right, as far as I could find out, libva doesn't support static linking. But wouldn't that be covered if I did a gpl-shared build with your environment? Or am I confusing shared libraries and dynamic linking somehow?
Say I wanted to build an up to date ffmpeg with vaapi capability and then transfer it and all dependencies to my media server (also linux64) how do you think I'd have to approach that?

**Comment by BtbN** [comment] 2021-07-06 11:20
The shared libraries are also statically linked. Adding libva support would prevent them from working on a system without a recent enough libva installed.

**Comment by gpregger** [comment] 2021-07-07 12:01
Wait, I must not understand the difference between dynamic and static linking then. Isn't a library that is statically linked incorporated into the binary at link-time, and a dynamically linked library contains code that is fetched at run-time? Wouldn't a shared library be intrinsically dynamically linked then?

But besides that, assuming I have libva on my target system and my compiling system how would I go about configuring the build environment to link it? I naively tried adding --enable-vaapi to the configuration, but that wouldn't work...

**Comment by BtbN** [comment] 2021-07-07 12:17
This build-setup builds entirely in a container. What's installed on your host is irrelevant.
You'd have to write a script.d entry that grabs and builds libva in the correct version.

And even the shared ebuilds link all the dependencies statically. Otherwise I'd come with something like 50 or more other libs.
libva does seem to have an option to be linked statically. But I have no idea how well that works.

**Comment by BtbN** [comment] 2021-07-07 12:40
Checking the libva repo, https://github.com/intel/libva/blob/2.12.0/configure.ac#L165 disables building it as a static library.
The meson buildsystem does not define a static target either.
So building it as a static library is impossible, and thus it can't be included.
MFX support is enabled, so you might have some luck with that. But I remember that being quite a pain on Linux.

**Comment by BtbN** [comment] 2021-07-13 22:34
I've added the necessary libraries, but since I have no system to test this on, I have no idea if this at all works when linked statically.
Also only included the DRM interface, no X11, since that requires even more dependencies.
If it works, I'll look into the X11 bits.

**Comment by gpregger** [comment] 2021-07-14 17:53
Hey
I really appreciate the efforts, unfortunately it doesn't seem to work:
```
/usr/lib/ffmpeg-git/bin/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/card1 -autorotate 0 -i file:"/media/Movies/whatever.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -b:v 292000 -maxrate 292000 -bufsize 584000 -profile:v:0 high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "format=nv12|vaapi,hwupload,scale_vaapi=w=426:h=176:format=nv12" -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 128000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/82a1c9509c21df23ebbef66a6da88263%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/82a1c9509c21df23ebbef66a6da88263.m3u8"


ffmpeg version N-102967-g3f5d5c1c2d-20210714 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (crosstool-NG 1.24.0.394_3782373)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --disable-vulkan --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-mbedtls --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags='-pie -Wl,-rpath=\$\$ORIGIN -Wl,-rpath=\$\$ORIGIN/../lib' --extra-libs=-lgomp --extra-version=20210714
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  3.101 / 59.  3.101
  libavformat    59.  4.100 / 59.  4.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[AVHWDeviceContext @ 0x55c4acb9ba40] No VA display found for device /dev/dri/card1.
Device creation failed: -22.
Failed to set value '/dev/dri/card1' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

**Comment by BtbN** [comment] 2021-07-14 17:56
Make sure to set the loglegel to verbose or even debug, so all the complains from the vaapi hwcontext get logged.
Does the same commandline work with a regular build?
What vaapi version, and what i965 vaapi driver version do you have installed?

**Comment by sudo-nautilus** [comment] 2021-07-15 00:55
Not loglegel but loglevel

**Comment by gpregger** [comment] 2021-07-15 17:22
Hey, I noticed that Jellyfin seems to add the option `-vaapi_device /dev/dri/card1` instead of `-hwaccel_device /dev/dri/card1` so for debugging I changed that.
Output is here [https://pastebin.com/gs4DmgfW](https://pastebin.com/gs4DmgfW)

**Comment by BtbN** [comment] 2021-07-15 17:46
Hm, unfortunately that probably means that it just plain doesn't work with static linking.
I'll leave it in for the time being, maybe someone gets motivated to poke at it some more.

**Comment by gpregger** [comment] 2021-07-15 17:48
I understand, thanks for your efforts!

**Comment by BtbN** [comment] 2021-12-21 13:26
I've implemented some tricks dynamic runtime loading of libva and some other stuff in todays builds.
So there's a chance this might actually work now.

Can't test it myself for lack of vaapi capable system, so please report back!

**Comment by gpregger** [comment] 2021-12-21 13:55
> I've implemented some tricks dynamic runtime loading of libva and some other stuff in todays builds. So there's a chance this might actually work now.
> 
> Can't test it myself for lack of vaapi capable system, so please report back!

Cool :) I'll see that I can test it in the coming days and will report back!

**Comment by BtbN** [comment] 2021-12-23 12:25
Got confirmation from multiple people that this works now, so closing here again.
Feel free to still provide feedback, can always re-open if some broken edge case is still unfixed.

**Closed by BtbN** 2021-12-23 12:25 UTC

**Comment by gpregger** [comment] 2021-12-27 15:18
Hey, I just tested your latest ffmpeg (ffmpeg-master-latest-linux64-gpl.tar.xz) in my jellyfin docker container.
It wouldn't work out of the box, reporting that libva-drm.so.2 couldn't be found, so I added the lib path of jellyfin's own ffmpeg build to /etc/ld.so.conf so your ffmpeg could find it. After doing that it started happily vaapi-transcoding!

Thing is, I'm fairly sure that this is not how it is supposed to be, since that seems to defeat the purpose of supplying ffmpeg with your own statically linked libraries (again though, I'm not exactly a pro when it comes to these things...).

Should I be using a different package?

Here is the exact error:

````
implib-gen: libva-drm.so.2: failed to load library: libva-drm.so.2: cannot open shared object file: No such file or directory
ffmpeg: libva-drm.so.2.init.c:56: load_library: Assertion `0 && "Assertion in generated code"' failed.
````

**Comment by BtbN** [comment] 2021-12-27 15:51
vaapi and all the various X11 libs cannot be statically linked.
They explode horribly if you try, and fail to work entirely.
So it's now doing the next best thing: It delay-loads the systems shared libs on use. So you do need vaapi and X11 libs that match your driver stack installed on the system for it to work. There is no way around that.

So yes, that's working exactly as intended.

Not sure what you mean by jellyfin path though. All you need to do is install your systems libva package. And have vainfo working.

**Comment by gpregger** [comment] 2021-12-27 16:04
Oh, gotcha!
Jellyfin ship their own ffmpeg build which relies on shared libs in /usr/lib/jellyfin-ffmpeg/lib. I installed your package to /usr/lib/BtbN-ffmpeg and added /usr/lib/jellyfin-ffmpeg/lib to /etc/ld.so.conf so it would find these libraries, and that seems to work.
Thanks!
