### ISSUE TITLE
Not actually static linking?

### ISSUE THREAD

**Issue by luofalei** [BtbN/FFmpeg-Builds#120] opened 2021-12-08 16:17 UTC
When I run `ldd bin/ffmpeg` for the binary, it doesn't look like a statically compiled binary.
Some libraries are getting dynamically linked in as follows:
```
	linux-vdso.so.1 (0x00007ffce64e6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f90428c7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f90428c1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f904289e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f90426ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f904a188000)
	libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f9042680000)
```

If it were a totally static binary, ldd would return `not a dynamic executable`.

I was hoping this project would result in a completely portable 64-bit binary but it doesn't appear to. Thanks in advance.

**Comment by BtbN** [comment] 2021-12-08 16:27
You cannot sensibly statically link glibc, so those libraries are always 
bound to be dynamically linked.

**Comment by BtbN** [comment] 2021-12-23 12:25
Closing this here, since not statically linking glibc is working as intended and not reasonably avoidable without breaking a bunch of stuff.

**Closed by BtbN** 2021-12-23 12:25 UTC
