### ISSUE TITLE
since version N-99692-gde59826703 (2020-10-22) an error occurs when using nvidia "h264_nvenc" library in Windows

### ISSUE THREAD

**Issue by fldrks** [BtbN/FFmpeg-Builds#23] opened 2020-10-28 19:04 UTC
d:\user\Videos>D:\software\youtube-dl\ffmpeg.exe -i "D:\user\Videos\RVC Recordings\The deceived - Aflevering 1 (Seizoen 1)  VRT NU.mpg" -ss 00:00:03.000 -t 01:27:09.000 -c:v h264_nvenc -preset slow -c:a aac "D:\user\Videos\deceived\the deceived 1 01 aflevering 1.mp4"
ffmpeg version N-99692-gde59826703 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --enable-vulkan --enable-libvorbis --enable-amf --enable-libaom --disable-avisynth --enable-libdav1d --disable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --enable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libvidstab --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 60.100 / 56. 60.100
  libavcodec     58.111.101 / 58.111.101
  libavformat    58. 62.100 / 58. 62.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 88.100 /  7. 88.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
Input #0, mpeg, from 'D:\user\Videos\RVC Recordings\The deceived - Aflevering 1 (Seizoen 1)  VRT NU.mpg':
  Duration: 01:27:19.64, start: 0.409600, bitrate: 10347 kb/s
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Side data:
      cpb: bitrate max/min/avg: 13000000/0/0 buffer size: 5324800 vbv_delay: N/A
    Stream #0:1[0x1c0]: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (mp2 (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_nvenc @ 000001bd1744d140] Cannot get the preset configuration: invalid device (4): EncodeAPI Internal Error.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by BtbN** [comment] 2020-10-28 19:06
The Video SDK was updated around that time.
Make sure you are using the very latest nvidia driver.

**Comment by jewshawn2** [comment] 2020-10-30 12:54
I'm having the same problem.  I saw the error to update nvidia drivers.  So I updated drivers to latest 457.09.

Last build that worked for me is gyan.dev ffmpeg-4.3.1-2020-10-01-full_build.  But stopped working with latest gyan.dev build 2020-10-28-git-e5be4c5a88.

Then I tried BtbN ffmpeg-N-99793-gae9a1a9698-win64-gpl (2020-10-29) but I get the same error.

Most likely a problem in the ffmpeg code.
Sat, 17 Oct 2020 avcodec/nvenc: update driver versions for SDK 11.0

Might be fixed in today's Auto-Build
Thu, 29 Oct 2020 16:59:37 Timo Rothenpieler | avcodec/nvenc: all presets are SDK10 presets now

---------------------------------------

E:\Movies>ffmpeg -vsync 0 -hwaccel cuda  -i "E170.mp4" -vf "crop=1280:656:0:32" -c:v h264_nvenc -preset slow -profi
le:v high -rc vbr -rc-lookahead 400 -no-scenecut 1 -b_adapt 0 -cq 0 -c:a copy -y "E170 nvenc2.mp4"
ffmpeg version N-99793-gae9a1a9698 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64
-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-iconv --ena
ble-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig -
-enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --enable-avisynth
--enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --en
able-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-li
bmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-schannel
 --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-
libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DL
IBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 60.100 / 56. 60.100
  libavcodec     58.112.100 / 58.112.100
  libavformat    58. 64.100 / 58. 64.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 88.100 /  7. 88.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E170.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:31:06.72, start: 0.000000, bitrate: 5359 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 363 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 10:11 DAR 160:99], 4988 kb/s,
29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[h264_nvenc @ 00000029fdd33040] Cannot get the preset configuration: invalid device (4): EncodeAPI Internal Error.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parame
ters such as bit_rate, rate, width or height
Conversion failed!

**Comment by BtbN** [comment] 2020-10-30 13:02
I'm unable to reproduce this locally.
`./ffmpeg.exe -hwaccel cuda -hwaccel_output_format cuda -i ./1080_h264_test.mkv -vf scale_cuda=1280:-2 -c copy -c:v h264_nvenc -cq 18 -y out.mp4` is working fine for me on the latest build.

The commit you reference purely adds the new SDK 11 driver version, so ffmpeg does not print "(unknown)" for the required driver version. It has no functional differences.
The only thing used from SDK 11 so far is AV1 decoding via cuviddec.c.

**Comment by jewshawn2** [comment] 2020-10-30 13:23
Thank you for a quick reply and making windows builds.  Can you try to test with a "preset" option?  If I remove the preset option it works fine for me now.

-preset fast
-preset medium
-preset slow

**Comment by BtbN** [comment] 2020-10-30 14:01
Those are just aliases for p1/p4/p7 respectively, with slow also turning on multipass. So yes, they work just fine as well.

**Comment by BtbN** [comment] 2020-11-04 12:33
Is this still an issue after updating the driver?

**Closed** 2020-11-10 14:39 UTC
